;编程完成如下操作：程序中设置了数据段、附加段和堆栈段，三个段中分别定义了不同的字变量 ARRAY1，ARRAY2 和 ARRAY3，编程计算三个数据的和，并把结果存放到 ARRAY1中。
DATA SEGMENT
    ARRAY1 DW 1234H
DATA ENDS
EXTRA SEGMENT
    ARRAY2 DW 3456H
EXTRA ENDS
STACK SEGMENT
    ARRAY3 DW 6789H
STACK ENDS

CODE SEGMENT
    ASSUME DS:DATA,CS:CODE,ES:EXTRA,SS:STACK
START:
    MOV DX,DATA
    MOV DS,DX
    MOV DX,EXTRA
    MOV ES,DX
    MOV DX,STACK
    MOV SS,DX
    
    MOV AX,ARRAY1
    ADD AX,ARRAY2
    ADD AX,ARRAY3

    MOV AH,4CH
    INT 21H
CODE ENDS
    END START
